language: python
python:
  - "3.4"

# each line defined in env will create a new parallel test job on Travis
env:
  - DO_LINT=true DO_UNIT=true DO_FUNCTIONAL=false
  - DO_LINT=false DO_UNIT=false DO_FUNCTIONAL=true

install:
  - pip install -r requirements.txt

script:
  - DO_PYLINT_CMD="pylint app"
  - TEST_UNIT_CMD="nosetests -v --with-xcoverage --cover-package=app test/unit"
  - TEST_FUNC_CMD="nosetests -s -v test/functional"
  - TEST_BUILD_UNIT_CMD="./main.py build"
  - export CR_VERBOSE=1  # turns on stdout logging for master and slave services during functional tests

  - if [[ $DO_LINT == true ]]; then $DO_PYLINT_CMD; fi
  - if [[ $DO_UNIT == true ]]; then $TEST_UNIT_CMD; fi
  - if [[ $DO_FUNCTIONAL == true ]]; then $TEST_FUNC_CMD; fi
  - if [[ $DO_FUNCTIONAL == true ]]; then $TEST_BUILD_UNIT_CMD; fi

after_success:
  - coveralls

