sudo: false
language: python
python:
  - "3.4"

# each line defined in env will create a new parallel test job on Travis
env:
  - TARGETS="lint test-unit-with-coverage" COV_LABEL="unit"
  - TARGETS="test-integration-with-coverage" COV_LABEL="integration"
  - TARGETS="test-functional test-unit-via-clusterrunner" COV_LABEL=""

install:
  - make init

script:
  - export CR_VERBOSE=1  # turns on stdout logging for master and slave services during functional tests
  - make $TARGETS

after_success:
  - if [ -n "$COV_LABEL" ]; then bash <(curl -s https://codecov.io/bash) -cF $COV_LABEL; fi
