language: python
python:
  - "3.4"

env:
  - TEST_DIR=test/unit
  - TEST_DIR=test/functional

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests $TEST_DIR

